// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:good_old_solitaire/models/cards/solitaire_card.dart';
import 'package:good_old_solitaire/models/cards/suit.dart';
import 'package:good_old_solitaire/models/game/game_persistence_snapshot.dart';
import 'package:good_old_solitaire/models/hive_adapters.dart';
import 'package:good_old_solitaire/models/settings/animation_speed.dart';
import 'package:good_old_solitaire/models/settings/draw_cards_number.dart';
import 'package:good_old_solitaire/models/settings/draw_cards_position.dart';
import 'package:good_old_solitaire/models/settings/solitaire_settings.dart';
import 'package:good_old_solitaire/models/theme/card_back_theme.dart';
import 'package:good_old_solitaire/models/theme/card_front_theme.dart';
import 'package:good_old_solitaire/models/theme/solitaire_theme.dart';
import 'package:good_old_solitaire/models/theme/table_theme.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnimationSpeedAdapter());
    registerAdapter(CardBackThemeAdapter());
    registerAdapter(CardFrontThemeAdapter());
    registerAdapter(DrawCardsNumberAdapter());
    registerAdapter(DrawCardsPositionAdapter());
    registerAdapter(GamePersistenceSnapshotAdapter());
    registerAdapter(SolitaireCardAdapter());
    registerAdapter(SolitaireSettingsAdapter());
    registerAdapter(SolitaireThemeAdapter());
    registerAdapter(SuitAdapter());
    registerAdapter(TableThemeAdapter());
  }
}
